logging:
  level:
    root: WARN
spring:
  datasource:
    continue-on-error: true
    initialization-mode: always
    initialize: true
    password: ''
    platform: mysql
    url: jdbc:mariadb://localhost:3306/leiloes?serverTimezone=UTC
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MariaDB10Dialect
    hibernate:
      ddl-auto: none
